FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set neutron_base_packages = [
            'keepalived',
            'openstack-neutron',
            'openstack-neutron-lbaas',
            'openstack-neutron-ml2',
            'openvswitch',
            'python-openvswitch'
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set neutron_base_packages = [
            'iproute2',
            'keepalived',
            'neutron-plugin-ml2',
            'neutron-server',
            'openvswitch-switch',
            'neutron-lbaas-common',
            'python-openvswitch'
        ] %}

    {% endif %}

{{ macros.install_packages(neutron_base_packages | customizable("packages")) }}

    {% if base_distro in ['ubuntu'] %}

RUN mkdir -p /usr/share/neutron \
    && ln -s /etc/neutron/api-paste.ini /usr/share/neutron/api-paste.ini

    {% endif %}

{% elif install_type == 'source' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

        {% set neutron_base_packages = [
            'conntrack-tools',
            'dnsmasq',
            'dnsmasq-utils',
            'ipset',
            'keepalived',
            'openvswitch',
            'python-openvswitch',
            'uuid'
        ] %}

    {% elif base_distro in ['ubuntu', 'debian'] %}

        {% set neutron_base_packages = [
            'conntrack',
            'dnsmasq',
            'dnsmasq-utils',
            'iproute2',
            'ipset',
            'iptables',
            'iputils-arping',
            'keepalived',
            'openvswitch-switch',
            'python-openvswitch',
            'uuid-runtime'
        ] %}

    {% endif %}

{{ macros.install_packages(neutron_base_packages | customizable("packages")) }}

ADD neutron-base-archive /neutron-base-source
RUN ln -s neutron-base-source/* neutron \
    && useradd --user-group neutron \
    && /var/lib/kolla/venv/bin/pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /neutron \
    && mkdir -p /etc/neutron /usr/share/neutron /var/lib/neutron /home/neutron \
    && cp -r /neutron/etc/* /etc/neutron/ \
    && cp -r /neutron/etc/neutron/* /etc/neutron/ \
    && cp /neutron/etc/api-paste.ini /usr/share/neutron \
    && mv /etc/neutron/neutron/ /etc/neutron/plugins/ \
    && chown -R neutron: /etc/neutron /usr/share/neutron /var/lib/neutron /home/neutron \
    && sed -i 's|^exec_dirs.*|exec_dirs=/var/lib/kolla/venv/bin,/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin|g' /etc/neutron/rootwrap.conf

{% endif %}

RUN curl -O -L https://github.com/F5Networks/neutron-lbaas/releases/download/v10.0.0/f5.tgz \
    && tar xvf f5.tgz -C /usr/lib/python2.7/site-packages/neutron_lbaas/drivers/ \
    && curl -O -L https://github.com/F5Networks/f5-common-python/releases/download/v2.3.3/f5-sdk-2.3.3-1.el7.noarch.rpm \
    && curl -O -L https://github.com/F5Networks/f5-icontrol-rest-python/releases/download/v1.3.0/f5-icontrol-rest-1.3.0-1.el7.noarch.rpm \
    && curl -O -L https://github.com/F5Networks/f5-openstack-agent/releases/download/v10.0.0/f5-openstack-agent-10.0.0-1.el7.noarch.rpm \
    && curl -O -L https://github.com/F5Networks/f5-openstack-lbaasv2-driver/releases/download/v10.0.0/f5-openstack-lbaasv2-driver-10.0.0-1.el7.noarch.rpm \
    && rpm -ivh f5-icontrol-rest-1.3.0-1.el7.noarch.rpm f5-sdk-2.3.3-1.el7.noarch.rpm f5-openstack-agent-10.0.0-1.el7.noarch.rpm f5-openstack-lbaasv2-driver-10.0.0-1.el7.noarch.rpm

COPY neutron_sudoers /etc/sudoers.d/kolla_neutron_sudoers
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN usermod -a -G kolla neutron \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_neutron_sudoers \
    && touch /usr/local/bin/kolla_neutron_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_neutron_extend_start

{% block neutron_base_footer %}{% endblock %}
